### ISSUE TITLE
Unable to receive events

### ISSUE THREAD

**Issue by d99kris** [unixpickle/fbmsgr#3]
Hi,
Firstly, thanks for creating fbmsgr. It looks quite useful. :+1: 

I've played around with it a little bit and got basic things working (AllThreads, ActionLog, SendText, etc), however I'm unable to receive events.

I've tried both ReadEvent() and EventStream() without any luck. See attached minimal go programs reproducing the issue in `readevent.go` and `eventstream.go` (I had to append `.txt` for Github to accept them though).

When I run `readevent.go` I get the following output:
```
ReadEvent err: fbmsgr: read event: jsonForResp: response too short
```

When running `eventstream.go` I just get a steady stream of:
```
EventStream evt: <nil>
EventStream evt: <nil>
...
```

Any idea if I am doing something wrong? Or has FB perhaps changed its API?

[eventstream.go.txt](https://github.com/unixpickle/fbmsgr/files/4774113/eventstream.go.txt)
[readevent.go.txt](https://github.com/unixpickle/fbmsgr/files/4774115/readevent.go.txt)

**Comment by unixpickle** [comment]
The backend must have changed. Thanks for catching this!

I'm pretty busy these days, so it may take a while for me to get around to investigating. If anybody else wants to figure out the change, be my guest!

**Comment by d99kris** [comment]
Understand, thanks anyway for the quick answer.

**Comment by d99kris** [comment]
I don't really need facebook messenger capabilities anymore, so I will proceed to close this issue. Thanks anyway for the help!
